# Проектна зміна стану
[ChangeCodes]
0 = не змінюється (зберігається)
1 = реконструкція
2 = модернізація
3 = ліквідація
4 = демонтаж
5 = знесення
6 = закриття
7 = створення у короткостроковий період
8 = створення у середньостроковий період
9 = створення у довгостроковий період
