[KP]
# Комплексний план просторового розвитку території територіальної громади
roads = Автомобільні дороги
streets = Вулиці та дороги населених пунктів
parcel = Земельна ділянка
settlement = Населені пункти
hromada = Території територіальних громад
landuse = Угіддя
function_zoning_in = Функціональне використання територій існуюче
function_zoning_pr = Функціональне призначення територій проєктне
sanit_protect_zones = Санітарно-захисні зони
protect_zones = Охоронні зони

[GP]
# Генеральний план населеного пункту
streets = Вулиці та дороги населених пунктів
parcel = Земельна ділянка
settlement = Населені пункти
areas_in_red_lines = Території в червоних лініях
areas_in_blue_lines = Території в блакитних лініях
areas_in_green_lines = Території в зелених лініях
areas_in_yellow_lines_pg = Території в жовтих лініях
landuse = Угіддя
function_zoning_in = Функціональне використання територій існуюче
function_zoning_pr = Функціональне призначення територій проєктне
sanit_protect_zones = Санітарно-захисні зони
protect_zones = Охоронні зони

[DPT]
# Детальний план території населеного пункту
dpt_area = Територія, на яку розроблено ДПТ
function_zoning_in = Функціональне використання територій існуюче
function_zoning_pr = Функціональне призначення територій проєктне
streets = Вулиці та дороги населених пунктів
parcel = Земельна ділянка


