# Назви JSON файлів 

# Тематичні групи меню для попереднього вибору категорії
[LayerGroups]
Planning_elements = Елементи планування 
Landuse = Використання земель
Restrictions = Обмеження
Structures = Споруди
Transport_networks = Транспортна мережа
Engineering_networks = Інженерні мережі
Inf_social_objects = Інфраструктура: об`єкти соціального призначення
Inf_community_facilities = Інфраструктура: Комунальні об`єкти
Inf_tourism_objects = Інфраструктура: Туристичні об`єкти
Inf_engineering_objects = Інфраструктура: Інженерні об`єкти
Inf_transport_objects = Інфраструктура: Транспортні об`єкти
Inf_enterprise_objects = Інфраструктура: Виробничі об`єкти
Environment = Середовище
Engineering_preparation = Інженерна підготовка території
Historical_cultural = Історико-культурна спадщина
Civil_protection = Цивільний захист

[Planning_elements]
hromada = Території територіальних громад
starostynstvo = Території старостинських округів
settlement = Населені пункти
city_district = Райони у містах
dpt_area = Територія, на яку розроблено ДПТ
address = Адреси
named_ob = Поіменовані адресні об`єкти
function_zoning_in = Функціональне використання територій існуюче
function_zoning_pr = Функціональне призначення територій проєктне
planning_centres = Планувальні центри
planning_axes = Планувальні вісі
planning_forms = Планувальні утворення в населених пунктах
transport_corridors = Транспортні коридори
trans_cor_infl_zones = Смуги впливу транспортних коридорів
suburban_zones = Приміські зони
free_econom_zones = Вільні економічні зони
invest_areas = Інвестиційно привабливі території
state_reg_interest = Території державних та регіональних інтересів
support_areas = Території, розвиток яких потребує державної підтримки
education_zones = Зони обслуговування освітніми закладами
medical_zones = Зони обслуговування закладами охорони здоров`я
nuclear_power_plant_control_zones = Зони контролю АЕС
ecovillage = Території екопоселень

[Landuse]
lands = Контури земель
parcel = Земельна ділянка
sublease = Право суборенди
landuse = Угіддя
agro_landscape_groups = Агроландшафтні групи земель
landuse_violation = Території порушення складу угідь
land_conservation = Консервація земель
agro_soil = Агровиробничі групи ґрунтів
forest_belts = Лісосмуги
lands_massif = Масив земель сільськогосподарського призначення
landmanagement = Землевпорядні заходи

[Restrictions]
areas_in_red_lines = Території в червоних лініях
areas_in_blue_lines = Території в блакитних лініях
areas_in_green_lines = Території в зелених лініях
areas_in_yellow_lines_pg = Території в жовтих лініях
building_reg_lines = Території в лініях регулювання забудови
protect_zones = Охоронні зони
sanit_protect_zones = Санітарно-захисні зони
sanit_gaps = Санітарні відстані (розриви) від об`єкту
water_supply_protect_zones = Зони санітарної охорони джерел водопостачання
waterprotect_zones = Водоохоронні зони
bank_protect = Прибережні захисні смуги
beach_zones = Пляжні зони
shore_zones = Берегові смуги водних шляхів
canals_bands = Смуги відведення гідротехнічних споруд
pzf_pg = Території та об`єкти природно-заповідного фонду
pzf_zon = Зонування територій та об`єктів природно-заповідного фонду
pzf_protected_zones = Охоронні зони об`єктів природно-заповідного фонду
pzf_reserve = Території, зарезервовані з метою наступного заповідання
health_protect_zones = Зони санітарної охорони курортів
avia_limits = Авіаційні, радіолокаційні обмеження
radiactive_limits = Радіаційні обмеження
spec_landuse_zones = Зона особливого режиму використання земель
heritage_protect_zones = Зони охорони пам`яток культурної спадщини
world_heritage_buf = Буферні зони об`єктів всесвітньої спадщини
hist_cult_conserv = Історико-культурні заповідники
hist_cult_area = Історико-культурні заповідні території
archeolog_protect_ter = Охоронювані археологічні території
historic_areals = Історичні ареали населених місць
expropriat_areas = території примусового відчуження

[Structures]
str_residential = Житлові будівлі
str_public = Громадські будівлі та споруди
str_industrial = Виробничі будівлі та споруди
str_transport = Будівлі та споруди транспорту
str_engineering = Будівлі та споруди інженерного забезпечення
str_hydro_pg = Гідроінженерні споруди
str_hydro_l = Гідроінженерні споруди
str_hydro_p = Гідроінженерні споруди
str_restrict = Спеціалізовані споруди
str_grounds = Функціональні майданчики
str_other = Інші будівлі та споруди
 
[Transport_networks]
roads = Автомобільні дороги
streets = Вулиці та дороги населених пунктів
spec_roads = Спеціалізовані дороги та проїзди
forest_roads = Польові та лісові дороги
trails = Мережа доріжок
railways_main = Залізниці магістральні
railways_local = Залізниці місцеві
trolleybus_lines = Тролейбусні лінії
main_oil_pipes = Магістральні нафтопроводи
main_gas_pipes = Магістральні газопроводи
main_products_pipes = Продуктопроводи
main_water_pipes = Магістральні водопроводи

[Engineering_networks]
main_power_lines = Магістральні лінії електропередачі
local_power_lines = Лінії місцевих електромереж
local_gas_pipes = Розподільні газопроводи
heating_pipes = Місцеві мережі теплопостачання
water_supply = Місцеві водопроводи питного водопостачання
water_tech_supply = Місцеві водопроводи технічного водопостачання
sewerage = Трубопроводи каналізаційних мереж
rain_water_sewer = Трубопроводи дощової каналізації
main_telecom_lines = Магістральні телекомунікаційні лінії
local_telecom_lines = Лінії місцевих телекомунікаційних мереж
main_melioration_nets = Канали магістральних меліоративних систем

[Inf_social_objects]
objects_public = Адміністративно-управлінські заклади
objects_research = Науково-дослідні, проєктні та вишукувальні заклади
objects_education = Освітні заклади
objects_medical = Заклади охорони здоров`я
objects_pharmacy = Фармацевтичні заклади
objects_social_protect = Заклади соціального захисту населення
objects_culture = Об`єкти культури та мистецтва
objects_religious = Культові об`єкти
objects_monuments = Монументи, скульптури
objects_sport = Спортивні об`єкти
objects_banks = Фінансові установи
objects_trade = Заклади торгівлі
objects_catering = Заклади громадського харчування
objects_home_service = Заклади побутового обслуговування
objects_veterinary = Ветеринарні лікарні
meteostations = Основні метеостанції державної мережі спостережень
geodetic_points = Геодезичні пункти

[Inf_tourism_objects]
hotels = Заклади короткострокового проживання
resort_objects = Санаторно-курортні та оздоровчі заклади
sport_fishery_objects = Об`єкти любительського і спортивного рибальства
beach_objects  = Пляжі
winter_resourts = Комплекси зимових видів спорту
tour_routes = Туристичні маршрути

[Inf_community_facilities]
housing_offices = Житлово-експлуатаційні організації
fire_stations = Пожежно-рятувальні підрозділи
ritual_services = Організації з надання ритуальних послуг
cemeteries = Кладовища
crematoria = Крематорії
animal_burial_grounds = Місця захоронення трупів тварин
garbage_grounds = Місця видалення відходів
recycling_object = Підприємства поводження з відходами
animal_shelters = Притулки для тварин
public_toilets = Громадські туалети

[Inf_enterprise_objects]
innovative_objects = Інноваційно-виробничі об`єкти
industry_objects = Промислові підприємства
livestock_objects = Підприємства тваринництва
plant_cultivation_objects = Підприємства рослинництва
other_agro_objects = Інші сільськогосподарські об`єкти
forestery_objects = Лісогоподарські об`єкти
fishery_objects = Рибницькі підприємства
hunting_objects = Мисливські об`єкти
storage_objects = Складські об`єкти

[Inf_transport_objects]
avia_transport = Об`єкти повітряних перевезень
rail_transport = Об`єкти залізничних перевезень
auto_transport = Об`єкти автотранспортних перевезень
water_transport = Об`єкти водного транспорту
transport_enterprises = Транспортні підприємства
railways_obj = Об`єкти на залізничних мережах
trollyebus_service = Об`єкти обслуговування тролейбусних ліній
runway_service = Об`єкти обслуговування злітно-посадкових смуг
autoservices = Пункти сервісу на автошляхах (комплекси автосервісу)
petrol_stations = Автозаправочні станції
techservice_stations = Станції технічного обслуговування
garages = Гаражі
car_park = Автостоянки для постійного зберігання автомобілів
trucks_grounds = Майданчики для відстою вантажного автотранспорту
transport_storage = Транспортно-складські комплекси
logistic_centres = Логістичні центри
terminals = Термінали
crossborder = Пункти пропуску через державний кордон
bridge_objects_p = Локалізація мостових переходів та шляхопроводів
bridge_objects_l = Об`єкти мостових переходів та шляхопроводів
tunnel_objects_p = Локалізація тунелів
tunnel_objects_l = Об`єкти тунелів
interchange = Транспортна розв`язка
public_transport_routes = Маршрути громадського транспорту
public_transport_stops = Зупинки громадського транспорту

[Inf_engineering_objects]
power_plants = Електростанції
power_objects = Об`єкти систем електрозабезпечення
oil_pipes_objects = Об`єкти на нафтопроводах
product_pipes_objects = Об`єкти на продуктопроводах
gas_pipes_objects = Об`єкти на газопроводах
communication_objects = Об`єкти зв`язку на трубопроводах
main_water_objects = Об`єкти на магістральних водопроводах
local_water_objects = Об`єкти місцевих водопровідних мереж питного водопостачання
local_techwater_objects = Об`єкти місцевих водопровідних мереж технічного водопостачання
heating_objects = Об`єкти на мережах теплопостачання
sewerage_objects = Об`єкти на каналізаційних мережах
sew_treat_plants = Каналізаційні очисні споруди
rain_sewer_objects = Об`єкти дощової каналізації
telecom_objects = Телекомунікаційні об`єкти

[Environment]
climate = Поширення кліматичних показників
countur = Горизонталі
river = Водотоки
waterb = Водойми
minerals_p = Родовища корисних копалин
minerals_pg = Території залягання корисних копалин
urban_dev_zones = Території за ступенем містобудівної цінності
watershed = Водозбірні басейни
mining_allocation = Гірничі відводи
mining_spec_permit = Спеціальні дозволи на користування надрами
pollution_objects = Основні забруднювачі
degraded_soils = Ареали поширення деградованих та еродованих ґрунтів
pollution_areas = Зони забруднення компонентів довкілля
radionuclide_hazard = Зони наднормативних рівнів іонізуючих випромінювань
techno_load = Техногенне навантаження
econet = Структурні елементи екологічної мережі
pzf_p = Об`єкти природно-заповідного фонду
emerald_network = Території Смарагдової мережі
unesco_nature_p = Природні об`єкти всесвітньої спадщини ЮНЕСКО
unesco_nature_pg = Території природних об`єктів всесвітньої спадщини ЮНЕСКО
intern_wetlands_p = Водно-болотні угіддя, що мають міжнародне значення
intern_wetlands_pg = Території водно-болотних угідь, що мають міжнародне значення
landscape_assesm = Оцінювання ландшафтних умов
green_pg = Озеленення
green_p = Об`єкти озеленення
env_conflict_res_p = Вузли можливих конфліктів господарської діяльності та довкілля
env_conflict_res_pg = Зони можливих конфліктів господарської діяльності та довкілля
env_aim = Оцінювання пріоритетності використання та охорони довкілля
env_protect_meas_p = Локалізація проведення заходів з охорони довкілля
env_protect_meas_l = Лінії проведення заходів з охорони довкілля
env_protect_meas_pg = Території проведення заходів з охорони довкілля
env_monitoring_p = Пункти моніторингу стану довкілля
env_monitoring_pg = Ареали моніторингу стану довкілля

[Engineering_preparation]
slope = Ухили земної поверхні
natural_hazards_areas = Ареали поширення небезпечних природних процесів
natural_hazards_points = Локалізація небезпечних природних процесів
loess_sediments_pg = Розповсюдження лесових порід, що мають властивість до просідання
disturbed_areas = Порушені території
melioration = Території меліорації
eng_protect_measures_pg = Ареали захисту території від небезпечних природних процесів
eng_protect_measures_l = Лінії захисту території від небезпечних природних процесів
eng_protect_measures_p = Локалізація захисту території від небезпечних природних процесів
recultivation = Рекультивація порушених територій
recultivation_allocation = Місця рекультивації порушених територій
eng_protect_other_pg = Інші проєктні заходи з інженерної підготовки та захисту території
eng_protect_other_l = Інші проєктні заходи з інженерної підготовки та захисту території
eng_protect_other_p = Інші проєктні заходи з інженерної підготовки та захисту території
ref_point = Опорні точки
vert_pl_slopes = Ухили вертикального планування

[Historical_cultural]
historic_rajon = Історичні райони населеного пункту
historic_build = Історична забудова
heritage_monuments = Пам`ятки культурної спадщини
heritage_mon_areas = Визначні місця - пам`ятки культурної спадщини
dominant_build = Містобудівні домінанти (визначні споруди)
disharmony = Дисгармонійні (дисонуючі) будівлі та споруди
lost_objects = Значні втрачені об`єкти
compos_axes = Планувально-композиційні осі
compos_nodes = Планувально-композиційні вузли
urban_space_types = Характерні типи міських просторів
monuments_view_areas = Зони огляду пам`яток архітектури
thresholds = Характерні відстані (якісні пороги) видового розкриття пам`яток архітектури
review_point = Оглядові точки
review_axes = Оглядові осі
review_fronts = review_fronts
view_zones = Зони формування видів

[Civil_protection]
strong_destructions_zones = Зони можливих сильних руйнувань
weak_destructions_zones = Зони можливих слабких руйнувань
hazard_radioact_pollut = Зони можливого небезпечного радіоактивного забруднення
safe_areas = Безпечні райони
catastrophic_flood_areas = Зони можливого катастрофічного затоплення
np_in_catastr_flood_areas = Населені пункти в зоні можливого катастрофічного затоплення
evac_pop_distrib_areas = Території розміщення евакуйованого населення
nuclear_pollut_zones = Зона можливого небезпечного радіоактивного забруднення від АЕС
chem_hazad_point_objects = Хімічно небезпечні об`єкти з точковим джерелом забруднення
chem_point_obj_pollut_hazad_areas = Зона можливого хімічного забруднення від точкового ХНО
chemical_hazad_line_objects = Хімічно небезпечні об`єкти лінійної протяжності
chemical_line_hazad_areas = Зона можливого хімічного забруднення від ХНО лінійної протяжності
ammunition_stores = Склади військового озброєння (засобів ураження)
ammunition_stores_impact_zones = Зона можливого ураження у випадку надзвичайної ситуації на складах боєприпасів
reserves_stores = Бази та склади матеріально-технічних, продовольчих та інших резервів
civil_protect_objects_pg = Об`єкти, що належать до категорій з цивільного захисту
civil_protect_objects_p = Розташування об`єктів, з категорій цивільного захисту
civil_protect_constr_pg = Захисні споруди цивільного захисту
civil_protect_constr_p = Розташування захисних споруд цивільного захисту
resid_build_shelter_areas = Території потенційної організації сховищ та ПРУ
underground_spaces = Зони формування підземного простору
roundabout_paths = Напрямки обходів у випадку руйнування основних шляхопроводів
evacuation_points = Пункти евакуації
evac_pop_distrib_points = Пункти розміщення евакуйованого/відселеного населення
evacuation_paths = Маршрути евакуації населення
injured_med_help_points = Пункти надання необхідної медичної допомоги постраждалим
fire_reservoirs_pg = Водойми для гасіння пожеж (штучні)
fire_reservoirs_p = Розміщення водойм для гасіння пожеж (штучні)
fire_wat_intake_place_pg = Облаштовані місця забору води для потреб пожежогасіння
fire_wat_intake_place_p = Розміщення облаштованих місць забору води для потреб пожежогасіння
potent_hazard_objects = Потенційно небезпечні об`єкти (ПНО)
high_hazard_objects = Об`єкти підвищенної небезпеки (ОПН)
potent_hazard_obj_impact_zone = Зона впливу ПНО
high_hazard_obj_impact_zone = Зона впливу ОПН

