# ПОСТАНОВА від 1 вересня 2021 р. № 926
# Про затвердження Порядку розроблення, оновлення, внесення змін та 
# затвердження містобудівної документації
# Допустимі місцеві систем координат відповідного регіону, однозначно зв’язані 
# з Державною геодезичною референцною системою координат УСК-2000, 
# в єдиній системі класифікації та кодування об’єктів містобудування 
# згідно з Класифікатором об’єктів містобудування та у форматі 
# бази геопросторових даних відповідно до вимог постанови Кабінету Міністрів України 
# від 9 червня 2021 р. № 632 “Про визначення формату електронних документів 
# комплексного плану просторового розвитку території територіальної громади, 
# генерального плану населеного пункту, детального плану території”
[LCS]
9831 = Автономна Республіка Крим
9832 = Вінницька область
9833 = Волинська область
9834 = Дніпропетровська область
9835 = Донецька область
9836 = Житомирська область
9837 = Закарпатська область
9838 = Запорізька область
9839 = Івано-Франківська область
9821 = Київська область
9840 = Кіровоградська область
9841 = Луганська область
9851 = Львівська область
9852 = Миколаївська область
9864 = Місто Київ
9865 = Місто Севастополь
9853 = Одеська область
9854 = Полтавська область
9855 = Рівненська область
9856 = Сумська область
9857 = Тернопільська область
9858 = Харківська область
9859 = Херсонська область
9860 = Хмельницька область
9861 = Черкаська область
9862 = Чернівецька область 
9863 = Чернігівська область
