 # Перелік допустимих кодів та відповідних їм значень
 # атрибуту state - Статус об'єкту
 [StateCodes]
 0 = не визначено
 1 = існуючий діючий
 2 = існуючий недіючий
 3 = на реконструкції
 4 = на стадії будівництва (реалізації)
 5 = зруйнований (руїни)
 6 = законсервований
 7 = занедбаний
 8 = проектний
 9 = проектний на короткостроковий період
10 = проектний на середньостроковий період
11 = проектний на довгостроковий період
12 = запроектований раніше
13 = аварійний
